#!/usr/bin/env php
<?php

set_time_limit(0);

define('COMMAND_PATH', __DIR__);

$loader = require_once __DIR__ . '/vendor/autoload.php';

use Leaf\Application;
use Leaf\Generator\BundleCommand;
use Leaf\Generator\EntityCommand;
use Leaf\Generator\CurdCommand;
use Symfony\Component\Console\Application as ConsoleApplication;

$app = new Application();
require __DIR__ . '/config/app.php';
$app->init();

$console = new ConsoleApplication();
$console->add(new BundleCommand());
$console->add(new EntityCommand());
$console->add(new CurdCommand());

if (file_exists(__DIR__ . '/config/command.php')) {
    $commands = require __DIR__ . '/config/command.php';
    foreach ($commands as $command) {
        $console->add(new $command);
    }
}

$console->run();
