

CREATE TABLE IF NOT EXISTS pre_user(
	id INT AUTO_INCREMENT PRIMARY KEY ,
	username VARCHAR(50) NOT NULL DEFAULT '' COMMENT '登录名称',
  password_hash VARCHAR(255) NOT NULL DEFAULT '密码哈希',
	nickname VARCHAR(255) NOT NULL DEFAULT '' COMMENT '昵称',
  avatar VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像',
	email VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱',
	mobile VARCHAR(50) NOT NULL DEFAULT '' COMMENT '手机',
	remember_token VARCHAR(255) DEFAULT '' NOT NULL COMMENT '记住',
	status INT NOT NULL DEFAULT 10 COMMENT '状态',

  created_at DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '新增时间',
  updated_at DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '修改时间',
	KEY username (username(20)),
	KEY email (email(20)),
	KEY mobile (mobile),
	KEY remember_token (remember_token(20))
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1001 COMMENT '用户';

